# -*- coding: utf-8 -*-
"""db_module

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16UWVhtg5-f_I8-BvKI7euPBxrSNU8N5b

### 1. 월별 매출 실적/ 이익
"""

import pymysql

def get_monthly(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
        SELECT DATE_FORMAT(sdate, '%m') AS `month`, 
            SUM(revenue) AS revenue, SUM(profit) AS profit
            FROM sales_books
            GROUP BY `month`
            ORDER BY `month`;
    """
    cur.execute(sql)
    results = cur.fetchall()

    cur.close()
    conn.close()
    return results

"""### 2. 거래처별 매출 / 실적"""

def get_company(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
        SELECT scompany, SUM(revenue) AS revenue, SUM(profit) AS profit
          FROM sales_books
          GROUP BY scompany
          ORDER BY profit;
    """
    cur.execute(sql)
    results = cur.fetchall()

    cur.close()
    conn.close()
    return results

"""### 3. 거래처의 판매상품 및 수량"""

def get_product_list(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
        SELECT scompany, pname, SUM(sunit) AS unit
          FROM sales_books
          group BY scompany, pname
          ORDER BY scompany;
    """
    cur.execute(sql)
    results = cur.fetchall()

    cur.close()
    conn.close()
    return results

"""#### 4. 제품별 판매수량/매출/이익"""

def get_products(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
          SELECT pname, sum(sunit) as total, SUM(revenue) AS revenue, SUM(profit) AS profit
            FROM sales_books
            GROUP BY pname
            ORDER BY total;
    """
    cur.execute(sql)
    results = cur.fetchall()

    cur.close()
    conn.close()
    return results

"""### 5. 카테고리별 매출/이익"""

def get_category(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
        SELECT pcategory, SUM(revenue) AS revenue, SUM(profit) AS profit
          FROM sales_books
          GROUP BY pcategory;
    """
    cur.execute(sql)
    results = cur.fetchall()

    cur.close()
    conn.close()
    return results

